version: 2

models:
  - name: stg_brand
    description: "staging brand"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
