version: 2

models:
  - name: staging_brand
    description: "Description of the stg_brand model"
    columns:
      - name: id
        description: "Unique identifier for the brand"
      - name: brand
        description: "Name of the brand"
